FROM golang:1.26-alpine3.22 AS build
WORKDIR /src
COPY cmd/zpr-diagnostics-query /src
RUN CGO_ENABLED=0 go build -trimpath -o /out/zpr-diagnostics-query main.go

FROM alpine:3.22
RUN apk add --no-cache ca-certificates
COPY --from=build /out/zpr-diagnostics-query /usr/local/bin/zpr-diagnostics-query
ENTRYPOINT ["/usr/local/bin/zpr-diagnostics-query"]
